### ISSUE TITLE
CLI Feature-Request: Set variables on command line

### ISSUE THREAD

**Issue by tobiasmuecksch** [ionic-team/capacitor-configure#17]
It would be nice, to be able to define variables using the command line interface.

For example like this:
`npx cap-config run config.yml -var BUNDLE_NAME=io.ionic.example-app -var APP_NAME='My App Name'`

Alternatively it would be sufficient if the CLI would respect environment variables, by preferring the cli input over the variables in the yml.

**Comment by mlynch** [comment]
It should respect env variables. Are you seeing something different?

**Comment by tobiasmuecksch** [comment]
For me it does not respect env vars. At least in the preview which is shown, when the CLI asks "Apply? (y/N)" 

This is how I tested it:

```
BUNDLE_ID_IOS=com.env-var.test; npx cap-config run platform-config.yml
```

To validate, that this syntax really works I double checked it like this:

```
BUNDLE_ID=com.env-var.test; echo $BUNDLE_ID_IOS
```

Further information on the syntax above: https://unix.stackexchange.com/a/56449

**Comment by mlynch** [comment]
Fixed in 1.0.17. Make sure you have the variables you are going to use defined in the `vars` section at the top of the yaml file.

Also we just started a discord with a Capacitor chat if you'd like to join! https://discord.gg/7muv6duf

**Comment by tobiasmuecksch** [comment]
Yup, I just tested it - and it works perfectly fine. Thanks!

**Comment by tobiasmuecksch** [comment]
@mlynch This seems to be broken again with version `1.0.27`

**Comment by mlynch** [comment]
Hmm, I don't see any changes since that release for that file. Will check this week. Possibly it's not seeing the env vars somehow?

**Comment by tobiasmuecksch** [comment]
@mlynch I have double checked it right now like this

`BUNDLE_ID=com.test.app ; npx @capacitor/configure run platform-config.yml`

and it doesn't work. cap-configure ignores the env var and uses the value in the `platform-config.yml`.

**Comment by mlynch** [comment]
Don't use the semicolon. Just tested and it's working great:

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/11214/145844736-21e03453-3505-4cfc-9460-3798c05c9732.png">

**Comment by tobiasmuecksch** [comment]
You are right. Without semicolon it seems to work. I wonder why it worked last week... Never mind - thanks for the support!
