### ISSUE TITLE
API and configuration

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor-configure#2]
Some of the feedback I've gotten so far is developers would like to be able to use this tool both from code and from configuration.

Initially, I've been focused on configuration as the primary way to use this tool (aka through a yaml file), but I can see the benefit of exposing a library for programmatic usage as well.

For example:

```javascript
import { Project } from '@capacitor/configure';

const platforms = await Project.getPlatforms();
await platforms.ios.setDisplayName('Display Name');
await platforms.ios.incrementBuild();
```

Would this be useful to you?

**Comment by dtarnawsky** [comment]
There is also a difference between what would be called with npx cap sync when it encounters a **new** plugin it hasn't applied changes to the native project yet (additions to the native project) and what is in capacitor.config.ts that are native project changes you intentionally want modify in a native project (bundle ids, versions etc)

**Comment by mlynch** [comment]
More I think about it, I think the API could be a `@capacitor/project` that is essentially an API for accessing and modifying whole Capacitor projects, and `@capacitor/configure` can use that under the hood. In that sense `@capacitor/configure` is just a simple tool and yaml-driven frontend to `@capacitor/project`.

**Comment by EinfachHans** [comment]
That would be great! I have a whitelabel App currently. Things i set via a custom Script in appflow currently:

- Custom UUID to identify the specific app in the backend to a ts export const file
- iOS:
  - **PRODUCT_BUNDLE_IDENTIFIER** of debug & release
  - CFBundleDisplayName
  - CFBundleShortVersionString
  - CFBundleVersion
  - **PROVISIONING_PROFILE_SPECIFIER** for debug and prod
  - Resources: Icon and SplashScreen (light and darkmode)
  - Also i have to replace the `GoogleService-Info.plist` to support Push Notifications (remove old & use new)
- Android:
  - `app_name`, `title_activity_main`, `package_name` and `custom_url_scheme` in **strings.xml**
  - `applicationId`, `versionName` and `versionCode` in **gradle file**
  - Resources: Icon (Adaptive & Notification) and SplashScreen (light and darkmode)
  - Update `google-services.json` file
- I also update the `capacitor.config.ts` with the bundleId and app name

**Comment by mlynch** [comment]
Thanks for the feedback I think the only things I'm missing now from this list are provisioning profiles, images which will be solved in the upcoming `@capacitor/assets` release, the Google plist one, and then some generic json modifications of other files. For now you can do about 85% of this list and I'll look into expanding it to handle the other needs.

**Comment by mlynch** [comment]
Closing as the original issue is settled (API is well defined and shipped)

**Comment by reslear** [comment]
@EinfachHans same need replace the `GoogleService-Info.plist` for stage/production
@mlynch good points, thank you,  have any news?)

**Comment by vscaiceanu-1a** [comment]
Hi @mlynch.
Any news on updating the Provisioning profiles? Is there any other way to update values in `ExportOptions.plist`?

Thanks

**Comment by emmapatterson** [comment]
> https://github.com/ionic-team/capacitor-configure/blob/main/lib/ios/project.ts

@EinfachHans Hi there, trying to do something very similar to what you have mentioned above. 

Been trying to use https://trapeze.dev/docs/ which seems to make it quite easy to inject config. Just wondering how exactly you set the following in android:

1. title_activity_main
2. package_name
3. custom_url_scheme

My guess is maybe they are being pulled directly from the `capacitor.config` but I haven't managed to get them overridden using trapeze.

Thanks in advance
Emma
