### ISSUE TITLE
configure: multiple issues with newly created platforms

### ISSUE THREAD

**Issue by tobiasmuecksch** [ionic-team/capacitor-configure#21]
# Current behavior
It seems, that configure does only manipulate the `App.entitlements` file if it already exists. If it does not exist, it does nothing. In the preview, the CLI does not mention any changes to the file.

And some more issues, as described [in the comment below ](https://github.com/ionic-team/capacitor-configure/issues/21#issuecomment-981377408)

# Expected behavior
I expected it to create the file under `ios/App/App/App.entitlements`.

# Reproduction
I've created a demo repo for you to quickly reproduce.

https://github.com/tobiasmuecksch/cap-configure-problem-demo

1. clone repo
2. run `npm run init`
    - _Info: This task installs npm packages, adds the `ios` and `android` platforms and runs `cap-configure`_
3. check the `ios/App/App/` folder, and you'll see, that the `App.entitlements` is missing.

**Comment by tobiasmuecksch** [comment]
I've observed two more issues with the demo repo above:

1.  `version` and `buildNumber` are not reflected in Xcode, although the platform files are manipulated (see screenshot below)
2. Even when I'm creating the App.entitlements file by adding a capability through Xcode, the file stays untouched by cap-configure

![Bildschirmfoto 2021-11-29 um 08 56 52](https://user-images.githubusercontent.com/1294854/143829449-2f24fc70-b87a-448c-80f7-42fe4c23b436.png)

**Comment by mlynch** [comment]
Thanks for the info! Will dig in and get these sorted

**Comment by mlynch** [comment]
Okay I see the issue. The `Info.plist` by default has a raw version number in here instead of a variable, so I'll need to account for that otherwise it'll override that

<img width="408" alt="image" src="https://user-images.githubusercontent.com/11214/143905489-299813c9-7351-4200-95b6-f0adc16f2aec.png">

**Comment by mlynch** [comment]
Fixed in 1.0.16 for both the build number and marketing version. One change: `setVersion` and `setBuild` are now async so add `await` before calling them. Thanks for the issue report!

**Comment by tobiasmuecksch** [comment]
@mlynch Thanks. But only the first mentioned problem is fixed.

With version `1.0.20` I still observe the following issues:

2. the Info.plist ist not changed at all, although I've defined stuff like `NSCameraUsageDescription` in the `platform-config.yml` 
3. Even when I'm creating the App.entitlements file by adding a capability through Xcode, the file stays untouched by cap-configure
4. the `applicationId` in `android/app/build.gradle` is not updated
5. as described in the original issue above, the `App.entitlements` file is neither created (if it does not exist) nor is it manipulated after it was created through Xcode
