### ISSUE TITLE
Info.plist is overwritten with empty object after latest changes

### ISSUE THREAD

**Issue by ksteuer** [ionic-team/capacitor-configure#26]
## Expected Behavior
Values set in the project are merged with existing values in Info.plist

## Actual Behavior
Values set in the project are merged with an empty object

## Steps to Reproduce the Problem
```
 ...
 const project = new CapacitorProject(config);
 await this.project.load();
 await this.project.ios?.setVersion(APP_TARGET_NAME, APP_BUILD_NAME, CURRENT_VERSION);
 await project.commit();
 ....
```
## Specifications

  - Version: 1.0.21
  - Platform: iOS

## Actual problem
I found that there is an issue with parsing Plist file: 
```
export async function parsePlist(filename: string) {
  const contents = await readFile(filename, { encoding: 'utf-8' });

  const parsed = plist.parse(contents);

  // If the plist is empty an empty array will come back
  // which is not what we want
  if (!(parsed as any[]).length) { //  <======= HERE
    return {};
  }

  return parsed;
}
```

We should not check parsed.length property as it usually is an object and as a result we always return empty object which later is merged with our new properties. Maybe lodash.isEmpty method would be relevant?

**Comment by mlynch** [comment]
Should be fixed in #27
