### ISSUE TITLE
Changes to files should have unix file separators instead of system default

### ISSUE THREAD

**Issue by kentora** [ionic-team/capacitor-configure#29]
We are using this to configure on windows, before sending it to a Mac to build. Right now I run into a problem when setting entitlements, where the 'CODE_SIGN_ENTITLEMENTS' in pbxproj is being set to App\App.entitlements instead of App/App.entitlements
(This line)
https://github.com/ionic-team/capacitor-configure/blob/c4df76cdf629a9b5f9f3c0964291c924c27d099d/packages/project/src/ios/project.ts#L290

This - and other places if such exists - where paths are being set, unix style seperators should be used.

**Comment by mlynch** [comment]
Good catch, will get this fixed

**Comment by mdledoux** [comment]
Oh wow - I just found this too, and I see @mlynch  just responded 8 days ago!
I see the same changes happening to my ios/App/Podfile
```diff
 def capacitor_pods
   pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
   pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
-  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
-  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
-  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
-  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
-end
-
-target 'App' do
-  capacitor_pods
-  # Add your Pods here
-end
+  pod 'CapacitorApp', :path => '..\..\node_modules\@capacitor\app'
+  pod 'CapacitorHaptics', :path => '..\..\node_modules\@capacitor\haptics'
+  pod 'CapacitorKeyboard', :path => '..\..\node_modules\@capacitor\keyboard'
+  pod 'CapacitorStatusBar', :path => '..\..\node_modules\@capacitor\status-bar'
+end^M
```
Oddly enough, no Android files got changed! \
I'm not sure how that is happening, or what I am doing to cause that - it seems to update on its own, and I keep doing a git checkout of the ios folder.  (Especially since this is happening when I'm working on Windows, but not Mac or Linux)


Will this simply be a minor upgrade, or will you provide instructions here? \
Or is there a config I can set or command I can run to override the default?

**Comment by kentora** [comment]
> I see the same changes happening to my ios/App/Podfile

I Think the change you are seeing here are caused by capacitor itself, not the configure module. I saw the same thing happen on my end too.

I do believe you are not seeing it automatically, but rather after a capacitor sync iOS command

**Comment by kentora** [comment]
It seems that the issuance be solved by using `convertToUnixPath` in cli/src/ios/update.ts:167 in the main capacitor repository

**Comment by mlynch** [comment]
Fixed in https://github.com/ionic-team/capacitor-configure/releases/tag/v1.0.27

**Comment by mdledoux** [comment]
@kentora,
> I do believe you are not seeing it automatically, but rather after a capacitor sync iOS command

Good catch - yes, I am seeing this happen automatically _when I run `ionic capacitor sync`_   :-)

Maybe when I'm on Windows, I could have specifically run `ionic cap sync android` so that it wouldn't mess with the ios stuff.  But hopefully the 1.0.27 fix solved this!

**Comment by mlynch** [comment]
And yes that issue looks related to the Capacitor CLI and my fix won't apply there
