### ISSUE TITLE
Info.plist: indentation and new line

### ISSUE THREAD

**Issue by cronn-leonn** [ionic-team/capacitor-configure#31]
The indentation of Info.plist files is changed from tabs (Xcode default) to spaces and an empty line is added at the end of the file. This will be reverted when the Info.plist is edited in Xcode again. The same applies to entitlements files.

<img width="1293" alt="Screenshot 2021-12-02 at 15 05 55" src="https://user-images.githubusercontent.com/93595039/144438005-506839c8-67e0-4ad0-a632-5faa6b4e43f3.png">

**Comment by mlynch** [comment]
Looks like this is hardcoded in the `plist` library we use so would need to somehow override that. Will have to backburner this for a bit

**Comment by mlynch** [comment]
Turns out they supported this and according to this comment this is the ideal formatting: https://github.com/TooTallNate/plist.js/issues/92#issuecomment-416003489

**Comment by cronn-leonn** [comment]
Thanks, this is really good!

I just tested it and found one little thing that Xcode does differently than the plugin: Xcode is adding an empty line at the end of the files.

<img width="1189" alt="Screenshot 2021-12-16 at 10 30 06" src="https://user-images.githubusercontent.com/93595039/146345903-4c2cd3de-fb54-4bef-aaa0-708b484a0014.png">
