### ISSUE TITLE
configure: Request for `-y` flag

### ISSUE THREAD

**Issue by tobiasmuecksch** [ionic-team/capacitor-configure#36]
In order to be able to use cap-configure in a CI pipeline, I'd like to request a `-y` flag, which suppresses all questions and automatically answers them with yes. Especially the `Apply changes?` question 😄

**Comment by mlynch** [comment]
There is a `-y` option.

`npm run cap-config my.yaml -- -y`

**Comment by tobiasmuecksch** [comment]
<img width="1328" alt="Bildschirmfoto 2021-12-13 um 08 24 20" src="https://user-images.githubusercontent.com/1294854/145769771-55c8f86e-5e3e-4c47-90c2-3a0f8020ee80.png">

Doesn't work for me.

**Comment by mlynch** [comment]
Hmm, working for me. Can you try installing `@capacitor/configure` directly and then create an npm script for it and call it like below?

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/11214/145876647-c9233768-aa24-4c7a-9e39-5a8bdfe9ec6d.png">
