### ISSUE TITLE
Quote strings before updating pbx

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor-configure#37]
Some pbx parsers are sensitive about strings being quoted (like the one used by cocoapods) and we're currently not quoting strings when writing back

**Comment by geoff-schultz** [comment]
Yes running into this issue now with PRODUCT_NAME in the project.pbxproj file needing quotes when running the cap sync or pod install commands.

**Comment by mlynch** [comment]
Fixed this. It will always read values without quotes, and write values that "need" to be quoted (based on the limited information around what values actually need to be quoted for pbx files, ex: http://danwright.info/blog/2010/10/xcode-pbxproject-files/)
