### ISSUE TITLE
How to specify appicon and splash screen

### ISSUE THREAD

**Issue by jabi11** [ionic-team/capacitor-configure#40]
Hi,
I want to use this tool to generate 2 apps from shared codebase. How can I specify appicon and splash screen for each app?

**Comment by mlynch** [comment]
There’s nothing built in for that in particular but this is a use case for the cordova-res tool and the in progress capacitor-assets update to that tool.

can you explain a bit what exactly you’re trying to do so we can make sure we design for your use case?

**Comment by jabi11** [comment]
I have 1 shared codebase and i’m generating 2 or more branded apps. They should have different app icons, splash screens, bundle ids and names. Now i have target/ flavor in native projects for each app. I tought that I can simplify that process with this tool.

Wysłane z iPada

**Comment by mlynch** [comment]
This will use available soon in https://github.com/ionic-team/capacitor-assets
