### ISSUE TITLE
npx cap-config stuck when gradle is references in config

### ISSUE THREAD

**Issue by marianobntz-silohub** [ionic-team/capacitor-configure#41]
Hello, I am running on Mac with OpenJdk:
`openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
`

When I run cap-config it is stuck, and I cannot see where is the problem. I see the java process of capacitor-gradle-parse.jar but nothing happens...

The gradle file is a standard file generated from capacitor 6... I am attaching the file

**Comment by marianobntz-silohub** [comment]
apply plugin: 'com.android.application'
apply plugin: 'com.google.firebase.appdistribution'
apply plugin: 'com.google.firebase.crashlytics'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    defaultConfig {
        applicationId rootProject.ext.silohubAppId
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode rootProject.ext.silohubBuild
        versionName rootProject.ext.silohubVersion
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        aaptOptions {
             // Files and dirs to omit from the packaged assets dir, modified to accommodate modern web apps.
             // Default: https://android.googlesource.com/platform/frameworks/base/+/282e181b58cf72b6ca770dc7ca5f91f135444502/tools/aapt/AaptAssets.cpp#61
            ignoreAssetsPattern '!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~'
        }
    }
    signingConfigs {
        debug {
            storeFile file("${project.gradle.gradleUserHomeDir.parent}/.android/debug.keystore")
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            storeFile file("${rootProject.buildDir}/../../../../build/tmp/android_sign.keystore")
            storePassword 'SILOHUB'
            keyAlias 'androidreleasekey'
            keyPassword 'SILOHUB'
        }
    }
    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            signingConfig signingConfigs.debug
            applicationIdSuffix ".debug"
            isDefault true
        }
        release {
            debuggable true
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            firebaseAppDistribution {
                artifactType "APK" // despues ver como cambiamos para prod
                appId "silohubFirebaseAppId"
                releaseNotesFile "${buildDir}/../../../tmp/release_notes.txt"
                groups "silohubFirebaseTesterGroups"
            }
        }
        prod {
            debuggable false
            minifyEnabled true
            matchingFallbacks = ['release']
        }
    }
    lintOptions {
        abortOnError true
        htmlReport true
        htmlOutput file("${buildDir}/reports/pepe/lint-results.html")
    }
}

repositories {
    flatDir{
        dirs '../capacitor-cordova-android-plugins/src/main/libs', 'libs'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "androidx.appcompat:appcompat:$androidxAppCompatVersion"
    implementation project(':capacitor-android')
    testImplementation "junit:junit:$junitVersion"
    androidTestImplementation "androidx.test.ext:junit:$androidxJunitVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$androidxEspressoCoreVersion"
    implementation project(':capacitor-cordova-android-plugins')
}

apply from: 'capacitor.build.gradle'

try {
    def servicesJSON = file('google-services.json')
    if (servicesJSON.text) {
        apply plugin: 'com.google.gms.google-services'
    }
} catch(Exception e) {
    logger.info("google-services.json not found, google-services plugin not applied. Push Notifications won't work")
}

**Comment by marianobntz-silohub** [comment]
if I run the same cap-config with java 8 it shows this error:
`Unable to apply changes Error: Unable to load or parse gradle file: ERR_SUBPROCESS_NON_ZERO_EXIT
    at GradleFile.parse (/Users/mariano/work/silohub/product-frontends/node_modules/@capacitor/project/dist/android/gradle-file.js:93:19)
    at async GradleFile.insertProperties (/Users/mariano/work/silohub/product-frontends/node_modules/@capacitor/project/dist/android/gradle-file.js:27:9)
    at async execute (/Users/mariano/work/silohub/product-frontends/node_modules/@capacitor/configure/dist/operations/android/gradle.js:15:13)
    at async executeOperations (/Users/mariano/work/silohub/product-frontends/node_modules/@capacitor/configure/dist/tasks/run.js:75:9)
    at async runCommand (/Users/mariano/work/silohub/product-frontends/node_modules/@capacitor/configure/dist/tasks/run.js:34:9)
    at async /Users/mariano/work/silohub/product-frontends/node_modules/@capacitor/configure/dist/index.js:52:13
    at async Command.<anonymous> (/Users/mariano/work/silohub/product-frontends/node_modules/@capacitor/configure/dist/util/cli.js:31:13)
Fatal error: Error running command
Error: Unable to load or parse gradle file: ERR_SUBPROCESS_NON_ZERO_EXIT
    at GradleFile.parse (/Users/mariano/work/silohub/product-frontends/node_modules/@capacitor/project/dist/android/gradle-file.js:93:19)
    at async GradleFile.insertProperties (/Users/mariano/work/silohub/product-frontends/node_modules/@capacitor/project/dist/android/gradle-file.js:27:9)
    at async execute (/Users/mariano/work/silohub/product-frontends/node_modules/@capacitor/configure/dist/operations/android/gradle.js:15:13)
    at async executeOperations (/Users/mariano/work/silohub/product-frontends/node_modules/@capacitor/configure/dist/tasks/run.js:75:9)
    at async runCommand (/Users/mariano/work/silohub/product-frontends/node_modules/@capacitor/configure/dist/tasks/run.js:34:9)
    at async /Users/mariano/work/silohub/product-frontends/node_modules/@capacitor/configure/dist/index.js:52:13
    at async Command.<anonymous> (/Users/mariano/work/silohub/product-frontends/node_modules/@capacitor/configure/dist/util/cli.js:31:13)
➜`

**Comment by marianobntz-silohub** [comment]
tried with node 14 and node 16 and still the same behaviour

**Comment by mlynch** [comment]
I think I fixed this issue. There was some problem with the internal process library I was using and was able to reproduce on a different gradle file. I rewrote the process execution part and it fixed the issue. Can you try the most recent release under the `next` tag?
