### ISSUE TITLE
Documentation: Override yaml file vars with env

### ISSUE THREAD

**Issue by kentora** [ionic-team/capacitor-configure#42]
Checking up on how to do this, I realized this is already implemented.

This could be documented better in the readme - in general the yaml file possibility is only described lightly

**Comment by reslear** [comment]
see please example

**Comment by sanderschnydrig** [comment]
@kentora how did you achieve this? It's not clear how to do this at all and looking at the basic.yaml example didn't enlighten me either.

**Comment by sanderschnydrig** [comment]
> > @kentora how did you achieve this? It's not clear how to do this at all and looking at the basic.yaml example didn't enlighten me either.
> 
> Vars are automatically replaced with env variables of the same name. Very easy, elegant and undocumented 😉

I have a `.env`file in the same folder as the `capacitor.yaml`:
```
BUNDLE_ID = com.example.app
PACKAGE_NAME = com.example.app
```

in my `capacitor.yaml` I have:
```
platforms:
  android:
    packageName: $PACKAGE_NAME
```

But the variable is undefined when I deploy with
```
npx @capacitor/configure run deploy-targets/example/capacitor.yaml -y
```

Any idea what I'm missing?

**Comment by sanderschnydrig** [comment]
@kentora I have a `.env`file in the same folder as the `capacitor.yaml`:
```
BUNDLE_ID = "com.example.app"
PACKAGE_NAME = "com.example.app"
```

in my `capacitor.yaml` I have:
```
platforms:
  android:
    packageName: $PACKAGE_NAME
```

But the variable is undefined when I deploy with
```
npx @capacitor/configure run deploy-targets/example/capacitor.yaml
```

Any idea what I'm missing?

**Comment by kentora** [comment]
> @kentora I have a `.env`file in the same folder as the `capacitor.yaml`:
> 
> 
> Any idea what I'm missing?


I don't believe .env files are supported, I think you have to load the env file first

**Comment by reslear** [comment]
@sanderschnydrig use [dotenv-cli](https://www.npmjs.com/package/dotenv-cli) and
`dotenv -- npx @capacitor/configure run deploy-targets/example/capacitor.yaml`

@kentora see please code example

**Comment by sanderschnydrig** [comment]
@reslear @kentora thanks guys it's working perfectly now.

.env HAS to be in root as far as I know.

`npx dotenv-cli -- npx @capacitor/configure run configuration/capacitor.yaml -y` is what I'm using now to get it working.

**Comment by kentora** [comment]
@reslear which code examples are you referring to? I can't seem to find any mention in the readme

**Comment by reslear** [comment]
@kentora part of the code that you use

**Comment by kentora** [comment]
@reslear something like this could be used

```

vars:
  BUNDLE_ID:
    default: io.ionic.wowzaStarter
  BUILD_NUMBER:
    default: 1

platforms:
  ios:
    targets:
      App:
        bundleId: $BUNDLE_ID
        version: 16.4
        buildNumber: $BUILD_NUMBER
```

On our CI server the env variable BUILD_NUMBER is set to the invocation number of each specific job.

**Comment by mlynch** [comment]
Tracking the `.env` suggestion in #42. Will update the docs shortly about the variable substitution, thanks.

**Comment by mlynch** [comment]
Added: https://github.com/ionic-team/capacitor-configure/blob/main/README.md#variables-and-environment-variables
