### ISSUE TITLE
Support variables with dot in YAML substitution

### ISSUE THREAD

**Issue by kentora** [ionic-team/capacitor-configure#43]
In CI/CD context we are using dot seperated env variables in order to group relevant settings. It would be nice to be able to use these to override vars in YAML files.

Example var name: ` tcappOne.ios.bundle.id:`
Example usage: `bundleId: $tcappOne.ios.bundle.id`

**Comment by mlynch** [comment]
I'm going to revert this. After thinking about it more, periods aren't allowed in bash env var names and supporting variables with periods makes actually using the variables much more difficult (see #112).
