### ISSUE TITLE
cap-config should get projectRootPath as argument

### ISSUE THREAD

**Issue by MarcBouteiller** [ionic-team/capacitor-configure#48]
Hi ! Thank for this project that I have discovered lately (after struggling with cordova-node-xcode ...)
I'd like to use @capacitor/configure but my workspaces are not in the default 'ios'/'android' path.

Could you provide a parameter to set the project root path ?

**Comment by mlynch** [comment]
Yes, I can definitely add that. I knew I'd need to eventually as this doesn't handle all the cases where a user has their projects in non-standard locations, it's also not reading the Capacitor configuration file, so I need to add that.

Taking a look at it right now, if it's easy I can get this done soon.

**Comment by mlynch** [comment]
Okay this should work now in `1.1.0`.

`npm run cap-config run config.yaml -- --projectRoot path/to/project/root`

This will also now load your `capacitor.config.ts` (or js/json) to find the ios and android directories inside of that root

Please give it a try and let me know if that works for you!

**Comment by mlynch** [comment]
Scratch that, 1.1.0 created some other issues so hold off and I need to figure out what exactly went wrong

**Comment by mlynch** [comment]
Okay 1.1.1 is out (latest is still on 1.0.28 to be safe). Would really appreciate if anyone could test @capacitor/configure@1.1.1 in place to make sure it's working for you.

We now load the Capacitor config file to find any custom project locations and, unfortunately, were missing a default for when the path fields weren't provided.
