### ISSUE TITLE
Bug: Update breaks yaml tool

### ISSUE THREAD

**Issue by sanderschnydrig** [ionic-team/capacitor-configure#49]
Hi Max

We've been using this great tool for a while for white labeling but since the most recent update the yaml configuration is broken. I suppose it might have to do with the capacitor.config.ts being taken into consideration, so I posted it down below for reference. For the meantime I solved it by using the previous version like this (**@1.0.31**)
```shell
npm_config_yes=true npx dotenv-cli -- npx @capacitor/configure@1.0.31 run configuration/capacitor.yaml -y
```

For example my ios entitlements are not being updated:
```yaml
entitlements:
          - com.apple.developer.associated-domains:
              [
                'applinks:$BASE_URL'
              ]
```

`capacitor.config.ts`:
```typescript
import { CapacitorConfig } from "@capacitor/cli"

const config: CapacitorConfig = {
  appId: `ch.example.app`,
  appName: `exampleApp`,
  webDir: `dist/app`,
  bundledWebRuntime: false,
  ios: {
    contentInset: `never`,
  },
  plugins: {
    SplashScreen: {
      launchAutoHide: false,
      androidScaleType: `CENTER_CROP`,
    },
  },
  server: {
    // hostname: 'ch.example.app', // this property will fix the ad displaying of audienzz on android
  },
  loggingBehavior: `production`, // 'none' | 'debug' | 'production'
}

export default config

```

**Comment by tomchiverton** [comment]
We noticed something similar where build numbers suddenly restarted from 1 until we pin'd  "@capacitor/configure" to "1.0.28" in package.json

Thing something changed in that package ?

https://forum.ionicframework.com/t/auto-incrementing-build-numbers-has-suddenly-stopped-working/220986

**Comment by mlynch** [comment]
Sorry about that. Do you have any error messages to share? Also looks like the tests will need to be updated to account for whatever issue this is.

for now stay on 1.0.28 and I’ll try to fix this in the next few days

**Comment by tomchiverton** [comment]
There's no errors. 

I posted build log extracts to https://forum.ionicframework.com/t/auto-incrementing-build-numbers-has-suddenly-stopped-working/220986 that clearly show it reading the numbers correctly but not actually adding to the build.

Ionic's support team also have a Zendesk issue with app and build details : 40665

**Comment by mlynch** [comment]
We've set latest back to 1.0.28 so keep using that for now until I figure out what broke

**Comment by mlynch** [comment]
Okay 1.1.1 is out (latest is still on 1.0.28 to be safe). Would really appreciate if anyone could test `@capacitor/configure@1.1.1` in place to make sure it's working for you.

We now load the Capacitor config file to find any custom project locations and, unfortunately, were missing a default for when the path fields weren't provided.

**Comment by sanderschnydrig** [comment]
@mlynch version 1.1.1 is working again for us with our project configuration, thank a bunch for your effort!

**Comment by tomchiverton** [comment]
v1.1.1 solved our issue
