### ISSUE TITLE
npm package versions are on 2.0.0

### ISSUE THREAD

**Issue by piotr-cz** [ionic-team/capacitor-configure#53]
Latest npm versions of [@capacitor/project](https://www.npmjs.com/package/@capacitor/project), [@capacitor/configure](https://www.npmjs.com/package/@capacitor/configure) and @capacitor/gradle-parse are 2.0.0 while package.json files show 2.0.3. Because of this it's not possible to update to 2.0.3 via npm.

Also the [releases](https://github.com/ionic-team/capacitor-configure/releases) page shows v1.0.28 as latest

**Comment by mlynch** [comment]
Releases haven't been updated with the move to changesets so that's fine, need to fix that. 2.0.3 was still a next tag. But thanks for the reminder I just updated it to latest

**Comment by piotr-cz** [comment]
Thanks

**Comment by piotr-cz** [comment]
Sorry to bug you again but now latest tag is 2.0,7 but on npm it's 2.0.3

**Comment by mlynch** [comment]
I know, I am not ready to release to latest just yet. You'll notice 2.0.7 is under the `next` tag. I will periodically do this when I add new features that are waiting broader testing.
