### ISSUE TITLE
inject intent-filter does nothing

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/capacitor-configure#55]
Hi, I'm trying to automatically add a new intent filter, specifically the one for this plugin: https://capacitorjs.com/docs/apis/app#android but it doesn't seem to work

```
platforms:
  android:
    manifest:
      - file: AndroidManifest.xml
        target: manifest/application/activity
        inject: |
          <intent-filter>
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              <data android:scheme="@string/custom_url_scheme" />
          </intent-filter>
```

tested with version 2.0.0 and 2.0.3

**Comment by mlynch** [comment]
This is fixed in `2.0.4@next`, can you try that version? It will now properly merge existing nodes. Thanks.

**Comment by Marius-Romanus** [comment]
Hello, I think it's not working well, since it's putting the intent-filter in the existing one, instead of creating a new one.

**Comment by mlynch** [comment]
Okay makes sense, I'll have to have two options for this command: `merge` and `inject`. Inject should always create new nodes rather than merging. Merging is a new operation that I added that I'll make separate

**Comment by mlynch** [comment]
@Marius-Romanus Try `2.0.5@next`. I've added a `merge` option which will merge and changed `inject` to _always_ inject. In the future I can add some smarts to deep compare with target nodes but for now this should handle what you need. Want to give that a try?

**Comment by Marius-Romanus** [comment]
Hello!, it works perfectly, thanks for the promptness!
