### ISSUE TITLE
Modify variables.gradle (and other gradle files?)

### ISSUE THREAD

**Issue by kentora** [ionic-team/capacitor-configure#63]
It would be nice to be able to modify variables.gradle in order to manage 3rd party versions.
My use case is setting SDK versions via yaml.

Could be a more general approach, allowing arbitrary gradle files to be modified.

**Comment by mlynch** [comment]
Just added support for this in 2.0.8, can you give that a try? See this issue for more info: https://github.com/ionic-team/capacitor-configure/issues/57
